### ISSUE TITLE
Usages of typealiases should be taken into account

### ISSUE THREAD

**Issue by technoir42** [autonomousapps/dependency-analysis-gradle-plugin#389]
**Plugin version**
0.72.1-SNAPSHOT

**Gradle version**
6.8.3

**Android Gradle Plugin (AGP) version**
4.2.0

**Describe the bug**
If module `app` depends on module `lib1` but uses only typealiases declared in module `lib1`, the plugin suggests removing the dependency on `lib1` from module `app`.

```
Advice for project :app
Unused dependencies which should be removed:
- implementation(project(":lib1"))
```

**To Reproduce**
Repro project: https://github.com/technoir42/dependency-analysis-bug-repro, branch: `typealias-bug`.

**Expected behavior**
The plugin doesn't suggest removing a dependency if only typealiases from that dependency are used.

**Comment by autonomousapps** [comment]
Thank you for the report.

**Comment by BraisGabin** [comment]
I was filling an issue related to this and then I found this one. I have all the issue filled so I'm pasting it here if it helps:

**Plugin version**
1.13.1

**Gradle version**
7.5.1

**(Optional) Android Gradle Plugin (AGP) version**
7.2.1

**`reason` output for bugs relating to incorrect advice**
```
----------------------------------------
You asked about the dependency 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4'.
You have been advised to remove this dependency from 'implementation'.
----------------------------------------

Shortest path from :libs-retrofit-utils to org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4 for compileClasspath:
:libs-retrofit-utils
\--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4

Shortest path from :libs-retrofit-utils to org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4 for runtimeClasspath:
:libs-retrofit-utils
\--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4

Shortest path from :libs-retrofit-utils to org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4 for testCompileClasspath:
:libs-retrofit-utils
\--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4

Shortest path from :libs-retrofit-utils to org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4 for testRuntimeClasspath:
:libs-retrofit-utils
\--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4

Source: main
------------
(no usages)

Source: test
------------
(no usages)
```

**Describe the bug**
In my code I use:

```kotlin
import kotlinx.coroutines.CancellationException
```

And that's all I use from `org.jetbrains.kotlinx:kotlinx-coroutines-core` on that module.

I imagine that the issue is that this `Exception` is a `typealias`:

```kotlin
public actual typealias CancellationException = java.util.concurrent.CancellationException
```

**To Reproduce**
Described above

**Expected behavior**
The plugin shouldn't advice to remove `org.jetbrains.kotlinx:kotlinx-coroutines-core`

**Context**
I could remove the dependency and use `java.util.concurrent.CancellationException` but that doesn't feel right.

**Comment by BraisGabin** [comment]
And, as an extra question, is there any way to workaround this? I'm doing this:

```kotlin
dependencyAnalysis {
    issues {
        all {
            onUnusedDependencies {
                exclude("org.jetbrains.kotlinx:kotlinx-coroutines-core")
            }
        }
    }
}
```

But that could create false negatives.
